###
### use this extension for testing the api:
###     https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###

@baseUrl = http://localhost:3000

### HEALTH CHECK

GET {{baseUrl}}/api/health

### CREATE USER

POST {{baseUrl}}/api/users/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "john@doe.test",
    "password": "supersavepassword"
}

### LOGIN USER

# @name login

POST {{baseUrl}}/api/users/signin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "john@doe.test",
    "password": "supersavepassword"
}

### CREATE MED #1

POST {{baseUrl}}/api/meds HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}

{
    "name": "med #1",
    "description": "test med",
    "expiredAt": "1750608175451",
    "category": "cat #1",
    "location": "loc #1"
}

### CREATE MED #2

POST {{baseUrl}}/api/meds HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}

{
    "name": "med #2",
    "description": "test med #2",
    "expiredAt": "1750608175461",
    "category": "cat #1",
    "location": "loc #1"
}

### CREATE MED #3

POST {{baseUrl}}/api/meds HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}

{
    "name": "med #3",
    "description": "test med #3",
    "expiredAt": "1750608175461",
    "category": "cat #2",
    "location": "loc #2"
}

### GET MEDS

# @name meds

GET {{baseUrl}}/api/meds HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}

### GET CATEGORIES

GET {{baseUrl}}/api/meds/categories HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}

### GET LOCATIONS

GET {{baseUrl}}/api/meds/locations HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}


### UPDATE MED #1

PUT {{baseUrl}}/api/meds/{{meds.response.body.$.[1].id}} HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}

{
    "name": "med #1 - updated",
    "description": "test med - updated",
    "productId": "1234",
    "expiredAt": "1750608175551",
    "category": "cat #1",
    "location": "loc #1"
}

### DELETE MED #1

DELETE {{baseUrl}}/api/meds/{{meds.response.body.$.[0].id}} HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{login.response.body.user.userId}}


### DELETE USER - Part 1

# @name user

POST {{baseUrl}}/api/users/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "john2@doe.test",
    "password": "supersavepassword"
}

### DELETE USER - Part 2

DELETE {{baseUrl}}/api/users/{{user.response.body.userId}} HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{user.response.body.userId}}

### DELETE USER - Part 3

POST {{baseUrl}}/api/users/signin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "john2@doe.test",
    "password": "supersavepassword"
}