###
### use this extension for testing the api:
###     https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###

@baseUrl = http://localhost:3000

### CREATE USER

POST {{baseUrl}}/api/users/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "john@doe.test",
    "password": "supersavepassword"
}

### DELETE USER - Part 1

# @name user

POST {{baseUrl}}/api/users/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "john2@doe.test",
    "password": "supersavepassword"
}

### DELETE USER - Part 2

DELETE {{baseUrl}}/api/users/{{user.response.body.user.userId}} HTTP/1.1
Content-Type: application/json
Accept: application/json
x-user-id: {{user.response.body.user.userId}}

### DELETE USER - Part 3

POST {{baseUrl}}/api/users/signin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "john2@doe.test",
    "password": "supersavepassword"
}