version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yeah-medication-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=${DATABASE_PATH}
      - CORS_ORIGIN_URL=${CORS_ORIGIN_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PW=${EMAIL_PW}
      - EMAIL_FROM=${EMAIL_FROM}
    restart: unless-stopped
    volumes:
      # Mountet dein lokales Projektverzeichnis ins Container-Arbeitsverzeichnis
      - yeah-medication-backend-data:/data

volumes:
  yeah-medication-backend-data:
    external: true
